#!/bin/zsh
# Xcode Cloud post-clone hook.
# Runs after Apple clones the repo, before Xcode operations start.
#
# Our ios/KPopHeardle.xcodeproj is .gitignored (generated by xcodegen
# from ios/project.yml). This script installs xcodegen and generates
# the project so Xcode Cloud has something to build.

set -euo pipefail

echo "==> ci_post_clone.sh starting"
echo "  macOS : $(sw_vers -productVersion)"
echo "  Xcode : $(xcodebuild -version | head -1)"
echo "  Repo  : ${CI_PRIMARY_REPOSITORY_PATH:-(unset)}"

cd "${CI_PRIMARY_REPOSITORY_PATH:-$(git rev-parse --show-toplevel)}"

if ! command -v xcodegen >/dev/null 2>&1; then
    echo "==> Installing xcodegen via Homebrew"
    brew install xcodegen
else
    echo "==> xcodegen already present: $(xcodegen --version)"
fi

echo "==> Generating ios/KPopHeardle.xcodeproj from ios/project.yml"
cd ios
xcodegen generate

echo "==> Verifying project file exists"
ls -la KPopHeardle.xcodeproj/project.pbxproj

echo "==> ci_post_clone.sh done"
